# Generated by Django 6.0.1 on 2026-02-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundtranfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_policy', models.PositiveIntegerField(unique=True)),
                ('new_policy_no', models.PositiveIntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='claim',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kyc_verified',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_name',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='premiumpayment',
            name='status',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(default=True, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(default=10001, max_length=50),
            preserve_default=False,
        ),
    ]
